//
// Created by nicol on 16/11/2023.
//

#ifndef COLECCI_N_DE_EJERCICIOS_FLUJO_C_MATEMATICAS_H
#define COLECCI_N_DE_EJERCICIOS_FLUJO_C_MATEMATICAS_H


class matematicas {

};


#endif //COLECCI_N_DE_EJERCICIOS_FLUJO_C_MATEMATICAS_H
